### ISSUE TITLE
problem!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [madeleine68/iTunes-Ramani#1]
please help me!!!

'next' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! itunes-next@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the itunes-next@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2022-04-02T09_28_55_759Z-debug.log

C:\Users\User\Downloads\iTunes-Ramani-main\iTunes-Ramani-main>npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @next/swc-linux-arm-gnueabihf@12.1.4: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  arm
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2022-04-02T09_29_05_891Z-debug.log

C:\Users\User\Downloads\iTunes-Ramani-main\iTunes-Ramani-main>

**Comment by madeleine68** [comment]
you can add `--force`  when you try to install the packages.

**Comment by KENPOKASMMA1982** [comment]
woow thanks so much!!!please can you make your amazing web appear music by date?for example love 2022 and appear just songs where released 2022!!!it would be greatttttttttttttt
